const Head = () => (
  <>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta
      name="mecanica"
      content="Generated by create next app developer: José Antonio"
    />
    <link rel="icon" href="/favicon.ico" />
  </>
);

export default Head;
